---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - optimizer.dev.builder
  resources:
  - costoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimizer.dev.builder
  resources:
  - costoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - optimizer.dev.builder
  resources:
  - costoptimizers/status
  verbs:
  - get
  - patch
  - update
