apiVersion: optimizer.dev.builder/v1alpha1
kind: CostOptimizer
metadata:
  labels:
    app.kubernetes.io/name: cost-operator
    app.kubernetes.io/managed-by: kustomize
  name: costoptimizer-sample
spec:
  # TODO(user): Add fields here
  name: "costoptimizer-sample"
  object: "job"
  schedule: "*/1 * * * *"
